### ISSUE TITLE
Reservation status not visible on mobile devices

### ISSUE THREAD

**Issue by ivandaudt** [alessandrotesoro/wp-restaurant-manager-lite#1]
Hello Alessandro,
I was demonstrating the reservation system to one of my waiters using an Android smartphone and noticed the reservation status is not visible on mobile devices.

Only reservation # and action links are visible on those devices.

He ended up approving a reservation which was already approved...
That's a potencial source of confusion and problems.

Can I suggest that you consider something other than those colored buttons/boxes to indicate reservation status on that panel? Something that works for mobile. The current one is only visible on PCs.

Tks, Ivan

**Comment by alessandrotesoro** [comment]
Hello,

Are you talking about the backend? If so, the columns are hidden by WP by default that's the behavior. It can be forced through css anyways.

I'm not looking to change the status indicator into the backend, but i would probably disable the "approve" link, if a reservation has already been approved.

Regards.

**Comment by ivandaudt** [comment]
That's a good idea.
I just learned that reservations not yet approved are shown as "Pending" in the list, while approved ones have no status indication. Hiding the "approve" link is a good way to prevent accidents on that screen.
