### ISSUE TITLE
No date/time picker on new reservation fm manage reservations panel?

### ISSUE THREAD

**Issue by ivandaudt** [alessandrotesoro/wp-restaurant-manager-lite#2]
Is there something wrong with my WP installation or there's really no date/time pickers on "New Reservation" screen, from Manage Reservations panel?

I just created a new reservation for a client, entering both date and time manually and got the following error:
"Warning: date() expects parameter 2 to be long, string given in /home/nonnacon/public_html/wp/wp-includes/functions.php on line 110

Warning: date() expects parameter 2 to be long, string given in /home/nonnacon/public_html/wp/wp-includes/functions.php on line 112

Warning: date() expects parameter 2 to be long, string given in /home/nonnacon/public_html/wp/wp-includes/functions.php on line 114

Warning: date() expects parameter 2 to be long, string given in /home/nonnacon/public_html/wp/wp-includes/functions.php on line 115

Warning: date() expects parameter 2 to be long, string given in /home/nonnacon/public_html/wp/wp-includes/functions.php on line 110

Warning: date() expects parameter 2 to be long, string given in /home/nonnacon/public_html/wp/wp-includes/functions.php on line 112

Warning: date() expects parameter 2 to be long, string given in /home/nonnacon/public_html/wp/wp-includes/functions.php on line 114

Warning: date() expects parameter 2 to be long, string given in /home/nonnacon/public_html/wp/wp-includes/functions.php on line 115

Warning: Cannot modify header information - headers already sent by (output started at /home/nonnacon/public_html/wp/wp-includes/functions.php:110) in /home/nonnacon/public_html/wp/wp-includes/pluggable.php on line 1178"

Your support is very welcome.
Tks, Ivan

**Comment by alessandrotesoro** [comment]
When clicking the date field, a date picker appears by default (screenshot http://cl.ly/aXWo) if it doesn't, something on your end is blocking the script to execute. I would suggest you check with browser console what's causing the issue, most likely some other js on your setup. 

The warning error, looks like it passed through my tests, i'll have a look at that tomorrow, as it's still a holiday here in UK.

**Comment by ivandaudt** [comment]
Alessandro,
Nothing is being blocked on my end for our own website. But I just realized what's the probable cause of this problem: https.

I run my regular website on http, but I also hv woocommerce and for that + admin functions I hv https.

I'm accessing our WP admin panel from https and js files are not delivered along with corresponding pages.

The request for js files should not use base website setting. It is http, while I might be under https. That will never work.

I had the exact same problem with another plugin and its scripts.

**Comment by alessandrotesoro** [comment]
I've just released an update, i'm not able to test SSL on my end, can you please test it on yours and let me know? You can download the update from here https://wordpress.org/plugins/wp-restaurant-manager/ or directly from your admin panel.

**Comment by ivandaudt** [comment]
Success. Date picker is working under ssl now.
But time picker is not!
Can you pls take a look at it too?

**Comment by ivandaudt** [comment]
Alessandro,
I hv a QA instance of my server, which also works under SSL.
I can give you access to it if you will, to perform tests by yourself.
Just let me know.
Rgds, Ivan

**Comment by alessandrotesoro** [comment]
The time field never had a time picker, it doesn't need one.
