### ISSUE TITLE
Upcoming reservations filter does not bring any data

### ISSUE THREAD

**Issue by ivandaudt** [alessandrotesoro/wp-restaurant-manager-lite#3]
Alessandro,
The "Upcoming Reservations" filter in Reservations Management panel does not bring any data, despite the fact there are reservations for future dates in our database.

Could it be an influence of our language settings? I'm running under pt_BR.

Tks, Ivan

**Comment by ivandaudt** [comment]
As further note to the point above:
The Upcoming Reservations panel starts as an empty screen. I was expecting all reservations >= today() to be there.

Buttons for Next 2 and 3 days seems to work fine, but that's counter intuitive. User's first impression is that the panel is not working at all...

**Comment by alessandrotesoro** [comment]
The tool only works when pressing these buttons ![](https://dl.dropboxusercontent.com/spa/fqbd10dq98t1met/hzh7_b_c.png)

Using the dates filter 
![](https://dl.dropboxusercontent.com/spa/fqbd10dq98t1met/489a273j.png)

has no effect on the "upcoming filter". The dates will filter the reservation based on the date the booking as made just like it works for every other post type in WordPress.

Furthermore the tool doesn't start as empty. It starts by displaying the reservations available "today".
